# Generated by Django 3.1.11 on 2021-12-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20211220_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_pic',
            field=models.ImageField(blank=True, default='default-product.png', null=True, upload_to=''),
        ),
    ]
